### ISSUE TITLE
"Add to .gitignore" option missing from context menu

### ISSUE THREAD

**Issue by pwilkin** [JetBrains/idea-gitignore#142]
I have a project with multiple repositories set up (for different modules) - don't know if this is relevant, but I don't get the context menu option "Add to .gitignore" for any of my files within the PSI tree. Using newest plugin and IDEA release build. Tried disabling all other plugins, still happening.

**Comment by hsz** [comment]
@pwilkin Do you have any of `*ignore` file in your project ? Can you provide me more details about your case ?

**Comment by pwilkin** [comment]
Yes, I have quite a few of them. At least one per VCS root. What would you like to know?

**Comment by pwilkin** [comment]
(I can provide you with any debugging info you want if you need it)

**Comment by pwilkin** [comment]
I'll try to give as much relevant info that I can think of:
* I made certain that the plugin loaded correctly. The icon near .gitignore files changed, I have the custom editor for .gitignore files, have the add .gitignore file action etc.
* Happens on both my IDEA installations, both on my laptop and my desktop. They share a similar project structure
* My project has multiple modules, each of them corresponding to a single project imported from Eclipse. They are all grouped within module groups.
* Each module has its separate VCS root. The root of the module is the root of the respective VCS (I have a single module on my desktop which does not conform to this rule)
* Each module has a .gitignore file in its root directory and at least one other .gitignore file somewhere else in the structure
* The .gitignore file itself is ignored
* All the .gitignore entries are marked gray an the inspection reports they are "never used"

**Comment by hsz** [comment]
> - The .gitignore file itself is ignored

Will it work properly if you remove this rule ?

**Comment by hsz** [comment]
@pwilkin Can you verify it with the latest `v1.3.3` version ?

**Comment by pwilkin** [comment]
Yes, it still persists (the context option is still missing). 

I might try to debug it if I get some free time.

**Comment by pwilkin** [comment]
Also, if it is of any help: the relative paths are recognized properly in the .gitignore file (marked as green). the absolute paths are not (marked as gray). So for example, if I have a .gitignore file in the root of my module VCS, then a "bin" entry is recognized properly, but a "/logs/" one is not.

**Comment by bamapookie** [comment]
I am using v1.4.1 with the latest IntelliJ IDEA, and I do not have this option as well.

**Comment by a200612** [comment]
Can confirm the issue aswell, context menu entry is missing.

**Comment by cwilli34** [comment]
This is also an issue in Rider.

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by themoffster** [comment]
This is an issue if you add a maven module to an existing one.
For example, if you 'open a maven project it is added to the project view. If you then through the maven projects view add another project, the context menu doesn't appear in the added project, but it does for the original.
In my experience the 'hide ignored files' doesn't work on these added projects either.

To recreate:
1. open a new project in IntelliJ
2. in the maven projects view add a new project (this will cause the project to appear in the project view (alt+1)
3. any files in the original project (from point 1 above) will have the "add to .gitignore" context menu option, but files in project from point 2 above will not.
4. files in project 2 will not auto-hide when already in the .gitignore file and looking in the project view

**Comment by jo-ka** [comment]
I can confirm the bug description by @themoffster with the latest IntelliJ (2018.1 build #IU-181.4203.550) and latest .gitignore plugin (v2.5.0) still.

**Comment by adstotz** [comment]
This is happening to me as well now (Idea v2019.1.1 and .ignore v3.1.2.191). Tried deleting local caches and rebuilding project directories as well as having tried cloning to a new directory directly from GitHub. Cannot add files to .gitignore from the context menu and plugin also doesn't recognize files I manually add to .gitignore when trying to hide them from the project file tree tool window.

**Comment by ametad** [comment]
Also I encounter this problem, after reinstalling my laptop with everything freshly installed.

I only have the **'unignore'** option, but none of my files can be added to the `.ignore` file:

![image](https://user-images.githubusercontent.com/1582541/82029368-32849800-9697-11ea-9cf1-7de44b3dc0d9.png)

Strange thing is that before I re-installed everything, adding did work correctly!

Here some extra info.

Plugin version:
![image](https://user-images.githubusercontent.com/1582541/82029836-d5d5ad00-9697-11ea-8abc-06bbf731ba68.png)

PhpStorm version:

![image](https://user-images.githubusercontent.com/1582541/82029962-0ae1ff80-9698-11ea-8301-64b9eadfbe95.png)

**Comment by ametad** [comment]
I just found out that the context menu does work in the case of

* an unversioned file
* in the 'commit' tab of PhpStorm

![image](https://user-images.githubusercontent.com/1582541/82044541-cfeac680-96ad-11ea-9165-8c8521266325.png)

Can this function *add to gitignore* also be used in the 'project' tab in PhpStorm?

**Comment by dmitriysmirnovspb** [comment]
@ametad since 2019.2 the Add to gitingore is the platform functionality, which does not require the .ignore plugin. See https://github.com/JetBrains/idea-gitignore/issues/587#issuecomment-514275657
It is git-related, so it is under GIt menu in the project tab.
<img width="896" alt="Screenshot 2020-05-15 at 14 26 51" src="https://user-images.githubusercontent.com/20108213/82046100-f2cea800-96b8-11ea-8874-cabb131206f5.png">

The unignore action comes from the plugin though, so it is in a different place. I think we will move it to the Git submenu also.

**Comment by dmitriysmirnovjb** [comment]
@ametad since 2019.2 the Add to gitingore is the platform functionality, which does not require the .ignore plugin. See #587 (comment)
It is git-related, so it is under GIt menu in the project tab.
<img width="896" alt="Screenshot 2020-05-15 at 14 26 51" src="https://user-images.githubusercontent.com/19227711/82046978-a4baa400-96ba-11ea-8bcd-d352b66d985a.png">

The unignore action comes from the plugin though, so it is in a different place. I think we will move it to the Git submenu also.

**Comment by ametad** [comment]
@dmitriysmirnovjb Thank you for the info. I found it!

**Comment by ametad** [comment]
BTW only "Unversioned Files" have the option **Git > Add to .gitignore > ..**. Is this indeed how it suppose to be? I guess to ignore already tracked files, the should first be removed from the repo and than added to the `.gitignore` file. Right?

**Comment by popandepo** [comment]
Having the same issue in Rider

**Comment by stepheneire** [comment]
This is really annoying in Rider 2023.3, it only works for "Unversioned Files". Can we please get "Remove From VCS" in the context menu for changes, that way we can remove first then ignore.
