### ISSUE TITLE
Filter out ignored files from search results

### ISSUE THREAD

**Issue by OliverJAsh** [JetBrains/idea-gitignore#178]
When I use Intellij’s "Find In Path" in my project, it shows me results that are listed as ignored.

Is it possible to promote these files to be excluded, so they do not show in the search results? Or is there a reason for not doing this? I can also do it manually using Intellij’s project settings, of course.

**Comment by toolforger** [comment]
There are use cases where you want to search ignored files as well, so this would have to be a search option.

**Comment by nathanbrauer** [comment]
Would love to see this feature... I was just asking about this on StackOverflow:
https://stackoverflow.com/q/47025599/808732

**Comment by toolforger** [comment]
Does IDEA offer a hook to add a new Search filter?
It may, given the structure of the Search dialogs (they are build in a manner that looks pretty flexible). I saw some pages talking about symbol search in source code, but nothing about simple text search, so maybe it's not possible.

**Comment by hsz** [comment]
I was investigating some possible solutions several times and it is not even possible to extend the Find toolbox in IDE or provide in any reasonable way any option to exclude some files easily.
I have to close this one - fingers crossed that this kind of the feature will be natively provided by JetBrains.

**Comment by dmitriysmirnovjb** [comment]
Here is a related request for the platform - https://youtrack.jetbrains.com/issue/IDEA-177598
