### ISSUE TITLE
Color Highlighting not working inside the .gitignore file

### ISSUE THREAD

**Issue by c33s** [JetBrains/idea-gitignore#245]
phpstorm 10.0.4
.ignore plugin  v1.5

in my phpstorm i have no colored syntax highlighting. everything is gray.

in the settings i can choose the colors and the preview looks perfect:
![settings](https://cloud.githubusercontent.com/assets/649209/17194759/05570ff8-545a-11e6-8b6a-a11d76d1c3ac.png)

after opening the gitignore file i see the correctly highlighted text but after 1-2 sec. the color is removed and everything is getting gray, line by line:
![gitignore-changing](https://cloud.githubusercontent.com/assets/649209/17194789/525e507c-545a-11e6-9b8b-675686198945.png)

in the end everything looks like this:
![gitignore](https://cloud.githubusercontent.com/assets/649209/17194776/315744ec-545a-11e6-9505-0a113c309db2.png)

i disabled all plugins except .ignore, tried with default and blackboard theme.

**Comment by c33s** [comment]
found a possible cause for this issue:

as i use the [workaround][1] for not having the `.idea` folder in my project folder, i have added a 2nd folder in `Settings > Directories > Add Content Root`

![ignore4](https://cloud.githubusercontent.com/assets/649209/17644130/58530f6e-617e-11e6-9a1b-6c5c7e1a9e11.png)

it looks like your awesome plugin has problems to deal with the multi directory structure.

in this example i haven't removed the main directory, holding the `.idea` folder, which i normally would remove and only work in the 2nd directory (project data directory).

in the main `.gitignore` the syntax highlighting is correct but for the 2nd-ary directory only the syntax highlighting for files in the root work, any other directories and files don't work.
another problem is the `Add to .gitignore file` is missing from the  context menu.

![ignore3](https://cloud.githubusercontent.com/assets/649209/17644134/bdb2fefa-617e-11e6-9b3b-5f5cdffbb7e8.png)


[1]: https://youtrack.jetbrains.com/issue/WI-343

**Comment by c33s** [comment]
the bug still exists as descibed in https://github.com/hsz/idea-gitignore/issues/245#issuecomment-239628062 

- .ignore plugin v 1.7.3
- phpstorm 2016.2.2

**Comment by hsz** [comment]
@c33s 

I have migrated to the native indexing mechanism provided by the IntelliJ and the performance should be much better for now (both performance and rules matching).

Can you please manually install the v2.0.0-rc.1 package from https://github.com/hsz/idea-gitignore/releases/tag/v2.0.0-rc.1 (zip file)?

**Comment by c33s** [comment]
@hsz yes. will do it in a few days

**Comment by c33s** [comment]
sadly the problem still exists.

- phpstorm 2017.1.3
- .ignore plugin v2.0.0-rc.1

**Comment by cwilli34** [comment]
This is also happening in Rider.

![screenshot_08 03 17_05](https://user-images.githubusercontent.com/9610352/28938161-3636faea-785b-11e7-9a48-406f5e6d42b2.png)

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by cwilli34** [comment]
This issue is still present with v2.1.1 in Rider.

**Comment by c33s** [comment]
still present in v2.6.1

**Comment by LordFoom** [comment]
Seeing this in Intellij Ultimate for v3.1.2

**Comment by hsz** [comment]
IntelliJ IDEA 2019.2 introduced native support for the dot-ignore files handling of Git (.gitignore), Mercurial (.hgignore), and Perforce (.p4ignore). Because of that, this issue is now obsolete.
