### ISSUE TITLE
Erroneous "unused entry inspection" warning when file is ignored by IntelliJ

### ISSUE THREAD

**Issue by AmsterdamFilho** [JetBrains/idea-gitignore#254]
If a file or folder is ignored by IntelliJ in Editor > File Types, the plugin will fire an "unused entry inspection" warning even if the entry is used.

Steps to reproduce: Go to Editor > File Types in IntelliJ. In the field "Ignore files and folders", add *.idea, so the IDE won't show these folders in the project view. Add *.idea to .gitignore. There will be an inspection warning that this entry is unused, even though the folder does exist and will be ignored by git.

**Comment by hsz** [comment]
@AmsterdamFilho Thank you for your report.

The problem with this case is that if IDE ignores some file itself - they are not available in the virtual tree of the project - and I cannot even access them from the IntelliJ API - so they appear to not existing.
I don't know if it's possible (and worth?) to discover them in any other way.

**Comment by AmsterdamFilho** [comment]
@hsz What if the plugin did not fire any warning for files that are ignored by IntelliJ? If the IDE is ignoring the file, maybe the plugin should ignore it too.

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by AmsterdamFilho** [comment]
Yes, it is. I am using IntelliJ 2017.2.2 and the version 2.1.1 of the plugin.
![screen shot 2017-08-26 at 16 52 54](https://user-images.githubusercontent.com/12434206/29744618-30674a4e-8a7f-11e7-86ea-e8adb318d340.png)
