### ISSUE TITLE
visibility of ignored files 

### ISSUE THREAD

**Issue by bliessens** [JetBrains/idea-gitignore#341]
IntelliJ's project view has a configuration option to 'Show excluded files'. When this option is enabled the excluded files are not displayed in the project view. I suspect idea-gitignore hides these files regardless of project view configuration.

**Comment by ssbarnea** [comment]
Somehow I am unable to convince IDEA to hide files from the project-view even when they are ignored in git. Funny, it does display them greyed so it does know they are hidden. How to hide them for good is still a mistery to me.

I don't want to mess with the general IDEA configuration, I just want to make  hide the gitignored files.

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by jorgheymans** [comment]
FWIW i noticed this as well (ignored files being visible even though i told the plugin to hide ignored files), it was not until i restarted intellij that the ignored files effectively became hidden.

**Comment by jorgheymans** [comment]
actually it's not all that clear. I have a project containing two git repositories, with identical gitignore. The hide ignored files only works in the second git repo, not in the first one. hopefully the screenshot makes this clear:

![image](https://user-images.githubusercontent.com/193792/31268084-0eecc8c8-aa7b-11e7-87f2-fceeb19524c1.png)

**Comment by Alfriadox** [comment]
I am also having this issue

**Comment by emolchanov** [comment]
I'm also having this issue too +1

**Comment by Indomitable** [comment]
In Rider showing All files should do not show ignored files when Hide ignored files is selected.

**Comment by mozesa** [comment]
**Hello**,

my problem is that it doesn't hide the files/dirs ignored.

Please see the image below.

![Untitled](https://user-images.githubusercontent.com/49973426/68482529-14e2fb80-023a-11ea-825c-ca8ca995923c.png)

**Comment by medington** [comment]
In IntelliJ 2019.2 I see both the issue mentioned above ("dist" not being hidden), as well as the fact that checking "Show Excluded Files" doesn't allow me to see the files inside of dist.

This seems easy to reproduce to me. Simply clone this repo and open the project: 

https://github.com/tommedema/serverless-mono-example

You'll need to install the packages and run the build command to populate the `dist` folder as well.

The behavior is slightly different depending on which view is used in the Project page ("Project Files" or "Project"). 

Would really appreciate some update on the disposition of this issue.

**Comment by hsz** [comment]
IntelliJ IDEA 2019.2 introduced native support for the dot-ignore files handling of Git (.gitignore), Mercurial (.hgignore), and Perforce (.p4ignore). Because of that, such an issue is now obsolete.

**Comment by reavon** [comment]
@hsz is this a default or is it a configurable item? I don't see it in settings and it doesn't seem to be default for me.
