### ISSUE TITLE
Projects in the IDE looks messed up now

### ISSUE THREAD

**Issue by BramDriesen** [JetBrains/idea-gitignore#393]
I would love to see a preference setting where you can turn off the messages in the files listing. Looks so messy now!

![image](https://user-images.githubusercontent.com/12573202/28752381-91e4953c-751d-11e7-9964-7ced55b2c06e.png)

**Comment by hsz** [comment]
@BramDriesen Have you tried to uncheck _Inform about ignored files that are still tracked_ in plugin's settings?

![image](https://user-images.githubusercontent.com/108333/28752508-dc098b46-7521-11e7-951c-9268a8812cdd.png)

**Comment by BramDriesen** [comment]
Just did, it doesn't remove the text from the project view.

**Comment by hsz** [comment]
Can you please restart the IDE?

**Comment by BramDriesen** [comment]
I did that since it prompted me to do so.

**Comment by hsz** [comment]
I meant restarting IDE after unchecking this option in settings (only plugins installation ask about restarting, so it was something different)

**Comment by damianlewis** [comment]
I'm having the same issue. Unchecking the option stated and restarting the IDE does remove the messages. However in a multirooted git project (project with several git repos) files that are tracked in a nested repo are no longer colour coded with the git status of that nested repo. The files are colour coded according to the outer repo.

**Comment by BramDriesen** [comment]
I'm indeed also in a multi git project. My outer git doesn't have this message, but the inside repo has this on every file + When editing you get the message you're editing an untracked file. While it is actually tracked. Quite confusing and annoying.

**Comment by hsz** [comment]
Closing due to removing this feature at all with v3.1.2
