### ISSUE TITLE
Plugin not honoring gitignore in subdirectory

### ISSUE THREAD

**Issue by sirianni** [JetBrains/idea-gitignore#478]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

The plugin is only honoring exclusions from a `.gitignore` file in the repository root.  `.gitignore` files in subdirectories are not honored.

### Steps to Reproduce
See screenshot.
![ignore](https://user-images.githubusercontent.com/381302/30551052-473f4e3e-9c67-11e7-9433-25cafcd2eb04.png)

**Expected behavior:** The files/directories should be marked as ignored in the IDE

**Actual behavior:** The files/directories are not ignored in the IDE

**Reproduces how often:** 100% of the time

### Versions

**Plugin:** 

```
2.2.1
```

**IDE:** 

```
IntellIJ 2017.2.4
```

**OS:** 

```
Ubuntu Linux
```

**Comment by kvn1234** [comment]
I found I have to dump my .idea folder and restart the IDE if I was using a previous version of the plugin.  But then it works fine from there.
