### ISSUE TITLE
Omit Ignored Files From Filtering

### ISSUE THREAD

**Issue by sgarfinkel** [JetBrains/idea-gitignore#502]
The best way to describe this problem is with an example. I'm using annotation processors to generate Java source code with Gradle. Gradle places the source code into the /build folder, which is, understandably, included in my .gitignore file. The .ignore plugin is filtering these generated folders, as a result.

Is there anyway to mark these folders to instead not be filtered by the plugin, without removing them from my .gitignore?

**Comment by hsz** [comment]
Unfortunately it cannot be implemented in an easy way. However, JetBrains team has taken over the gitignore related features in 2019.x so if your request is still valid, you can report this request in their issue tracker.
