### ISSUE TITLE
Cannot figure out how to show ignored files

### ISSUE THREAD

**Issue by abductedMind** [JetBrains/idea-gitignore#504]
### Prerequisites

* [x] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Cannot figure out how to show ignored files. I am uninstalling the plugin. If either somethings is added to documentation, or this feature is removed, I will reinstall the plugin.

```
Stack trace if available.
```

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:** _What you expect to happen_

**Actual behavior:** _What actually happens_

**Reproduces how often:** _What percentage of the time does it reproduce?_

### Versions

**Plugin:** 

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 
IntelliJ

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 

```
Information about operation system - type, version.
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._

**Comment by abductedMind** [comment]
I figured out the issue - was in project files view rather than project view. But where is documentation of the hide feature regardless?

**Comment by tifoha** [comment]
does anyone know how to disable the hiding of ignored files?

**Comment by mc-android-developer** [comment]
+1. It's a problem. I still want to see and edit ignored files. No point in hiding them. They should be visible by default.

**Comment by fuzzyweapon** [comment]
This seems like a bug for improving intellij usability.  I'm not 100% sure this is something in the scope of this plugin (aka not sure it can really address it, and even if so, wouldn't that just create more confusion for people who **do** know how to do this in the IDE already?).  But I'm not the person to be deciding that. :)

**Comment by hsz** [comment]
Bringing the hidden ignored files back can be don in the same place, where you can enable this feature.
Click with RMB on the Project in Project View and pick _Show ignored files_ on the bottom:

![image](https://user-images.githubusercontent.com/108333/65875603-e7c44300-e387-11e9-850b-10540bdd368d.png)
