### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by millerf** [JetBrains/idea-gitignore#505]
### Prerequisites

* [x] Plugin is in the latest version (2.3.2)
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Since the update it claims some files are in .gitignore while they aren't, and it also cancel all changes made on those files...

**Comment by hsz** [comment]
Can you be more specific and provide some steps to reproduce?

**Comment by hsz** [comment]
Closed due to inactivity.
