### ISSUE TITLE
"Add unversioned files" shortcut adds strange entries to .gitignore file

### ISSUE THREAD

**Issue by kosi2801** [JetBrains/idea-gitignore#507]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
When opening the .gitignore file the yellow bar at the top suggests "Would you like to add unversioned files to the .gitignore file?". When accepted it adds very strange entries which sound like they are coming from a user interaction message or error message text.
The entries added are "Würde xyz löschen" (german) and translate to "would delete xyz". See screenshots below.

### Steps to Reproduce

1. open .gitignore file
2. accept suggestion to add unverisioned files

**Expected behavior:** unversioned files are added

**Actual behavior:** Strange and disfunctional entries are added to the file

**Reproduces how often:** always in that particular project

### Versions

**Plugin:** 
2.3.2

**IDE:** 
IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.17, built on December 19, 2017

**OS:** 
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-19-generic

### Additional Information

The added text "Würde xyz löschen" is in German and translates to "would delete xyz".
![view before accept](https://user-images.githubusercontent.com/1632470/34198840-099d1c7a-e56c-11e7-84b6-8264ea01dc21.png)
![view after accept](https://user-images.githubusercontent.com/1632470/34198839-0983d8f0-e56c-11e7-806a-d5c23fb0152e.png)

**Comment by degree** [comment]
I have the same issue on
```
IntelliJ IDEA 2019.1 Beta (Ultimate Edition)
Build #IU-191.6014.8, built on March 5, 2019
IntelliJ IDEA EAP User
Expiration date: April 4, 2019
JRE: 11.0.2+159 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

**Comment by flying-sheep** [comment]
I assume you call `git clean -nd` without setting a locale and then remove leading occurances of `Would remove `, except that that’s not what it reads like in any language but english.

**Comment by hsz** [comment]
Thank you for reporting and investigation.
Unfortunately this feature was causing more problems and annoyed users a lot than it was helpful. Since v3.1.2 it is not longer present.

**Comment by daohewang** [comment]
I only want to know what I need to choose
