### ISSUE TITLE
the show members function of class file not working

### ISSUE THREAD

**Issue by MIMIEYES** [JetBrains/idea-gitignore#517]
### Prerequisites

* [X] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

_When I installed the igore plugin and restart IDE, the class show members function of the IDE failed. then I don't use it and restart IDE, it's normal._
![image](https://user-images.githubusercontent.com/15118554/36137262-63c48420-10cf-11e8-92e8-cb995b3c1439.png)

### Steps to Reproduce

1. _Installed the latest version's plugin_
2. _restart my IDE_
3. _class' show members not working_

**Expected behavior:** _all function are normal._

**Actual behavior:** _show members not working_

**Reproduces how often:** _100%_

### Versions

**Plugin:** 

```
Version: 2.4.0
```

**IDE:** 

```
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**OS:** 

```
Mac OS X 10.12.6
```

### Additional Information

_no more informations_

**Comment by hsz** [comment]
With the latest IntelliJ (2018.1) and plugin in v2.5.0 everything works fine:

![image](https://user-images.githubusercontent.com/108333/38658392-37a51354-3e25-11e8-893d-f58c24f8d9d7.png)

After switching to _IntelliJ IDEA 2017.3.4_ everything works fine too.

Can anyone else confirm this issue?

**Comment by MIMIEYES** [comment]
With the latest IntelliJ (2018.1) and plugin in v2.6.1, I found something else.
![image](https://user-images.githubusercontent.com/15118554/38768921-4a128f4e-402d-11e8-9d8f-afa0ff28e69d.png)
![image](https://user-images.githubusercontent.com/15118554/38768955-bd2e760a-402d-11e8-8460-dd6aea54ed51.png)

when i choose "show ignored files", everything works fine.

After switching to "hide ignored files", it can not working of "show members".

![image](https://user-images.githubusercontent.com/15118554/38768993-3eb4c4ea-402e-11e8-8b97-29aaae46c72e.png)
![image](https://user-images.githubusercontent.com/15118554/38768997-55a46570-402e-11e8-9a21-e56a7bb84a04.png)

**Comment by hsz** [comment]
@MIMIEYES that's helpful, thanks. I'll try to reproduce it this way.

**Comment by CrazyCoder** [comment]
https://youtrack.jetbrains.com/issue/IDEA-194385
