### ISSUE TITLE
Missing context menu entry for tracked-ignored files

### ISSUE THREAD

**Issue by zelding** [JetBrains/idea-gitignore#541]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

The `handle ignored and tracked files` menupoint is missing from the project tree context menu
Present in two separate versions of PHPStorm 2018

### Versions

**Plugin:** 

```
2.6.1
```

**IDE:** 

```
PhpStorm 2018.1.2
Build #PS-181.4668.78, built on April 25, 2018
JRE: 1.8.0_152-release-1136-b29 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-39-generic
```
and
```
PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-39-generic
```

**OS:** 

```
Linux Mint 18.3 Sylvia
MATE x64
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._

**Comment by hsz** [comment]
@zelding Thanks for creating this issue.
This context menu element appears only in case there is at least one file on the tracked-ignored list. Otherwise, it's not visible.

**Comment by magneticflux-** [comment]
I'm having the same issue, it seems like there's a desync where I have tracked-ignored files but nothing can be done about them using Intellij.

**Comment by hsz** [comment]
Currently this tracked-ignored feature is removed because of some incompatibilities and other problems related to the OS/FS/etc. Everything should be fine since v3.1.2.
