### ISSUE TITLE
FlasePositive when having cloned repos or submodule in working directory

### ISSUE THREAD

**Issue by qeqar** [JetBrains/idea-gitignore#556]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
the plugins don't now about submodules or cloned repos in working directory

I often have other repos cloned in my repo. because i don't want the repo commited in my project, i mostly put the root dir in the .ignore file.

but at every start i get the waring that i have files check in which are in the .ignore file

### Steps to Reproduce

1. new git repo
2. clone an other repo in a subdir
3. add subdir to .gitignore of the master project
4. start ide

**Expected behavior:**
No warning for files form other repos

**Actual behavior:** 
Warning on startup

**Reproduces how often:** 
Erery startuo

### Versions

**Plugin:** 

```
3.0.0.182
```

**IDE:** 

```
IU-182.3911.3
```

**OS:** 

```
Arch Linux
```
Thanks,
Mark

**Comment by hsz** [comment]
IntelliJ IDEA 2019.2 introduced native support for the dot-ignore files handling of Git (.gitignore), Mercurial (.hgignore), and Perforce (.p4ignore). Because of that, this issue is now obsolete.
