### ISSUE TITLE
request: add "all" versioned file into .gitignore as exclude

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/idea-gitignore#560]
hope can have a option action for this
for some Special usage

when we have 

.gitignore
```
*.js
```

files
```
aaa.js (in git)
bbb.js (not in git)
```

after this action

.gitignore has

```
*.js
!aaa.js
```

**Comment by hsz** [comment]
You can manually add selected files to the `.gitignore` as "unignore" with selecting several files in Project View, and picking _Add to .gitignore file (unignore)_ from the context menu:

![image](https://user-images.githubusercontent.com/108333/65876545-cebc9180-e389-11e9-9127-08f75f6b796e.png)

Following entries will be added:

![image](https://user-images.githubusercontent.com/108333/65876576-df6d0780-e389-11e9-845d-8c38e42a96ec.png)
