### ISSUE TITLE
One Ideas of "You are editing file which is ignored"

### ISSUE THREAD

**Issue by D-W-X** [JetBrains/idea-gitignore#563]
### Prerequisites

* [x ] Plugin is in the latest version
* [ ] Issue was not reported yet （It's maybe one have been solved. ）
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

    When I open a new file/project which is not been gitted (Maybe I just want to use it in my PC and learn something new so I don't want to upload it to github or somewhere else ), there is no .ignore file or else, but I got the prompt "You are editing file which is ignored".

### Steps to Reproduce

1. Creat a new file
2. Open it with IntelliJ IDEA 
3. Got this prompt

**Expected behavior:**

    I don't think this is (without .ignore file & get prompt ) necessary. (I recommend) the plugin should be stopped by itself instead of users (just as previous version).

**Actual behavior:** 

    Get prompt and the file in "Progect"(left) became gray.

**Reproduces how often:** 

    From today everytime I open the file without .igonre file

### Versions

**Plugin:** 

    3.0.0.182

**IDE:** 

    the IDEA version is "2018.2.4" 

**OS:** 

    Win10 

Thank you!

**Comment by DrankUser** [comment]
Same. I don't even have VCS in my local project, 'cause I'm using the derived VCS, so for me it's a real headache to turn on and off plugin while switching between projects.

**Comment by hsz** [comment]
It is possible to disable this feature in plugin's settings:

![image](https://user-images.githubusercontent.com/108333/65867471-c4dd6300-e376-11e9-8e3a-f7b889159ebe.png)
