### ISSUE TITLE
Too long `loading...` in Project view

### ISSUE THREAD

**Issue by zolotov** [JetBrains/idea-gitignore#564]
Version:  3.0.0.182

Feedback from a user:

> we have a mono-repo of go code, consisting of around 700 microservices each in their own folder. Each folder probably contains around ~10 files on average. The file tree is _extremely_ slow to load on the project pane. When I switch branches in git or try to view files inside a folder on the project pane, it often takes from 30 seconds up to a minute to show the files. It says "loading..." in the meantime. This means I'm unable to do any work with the IDE for about a minute every time I switch git branches

Disabling .ignore plugin fixes the issue. Content of the directories cannot be loaded until .ignore finished its business:

![image](https://user-images.githubusercontent.com/140920/47217051-c0ab7600-d3af-11e8-947b-57892786801c.png)

**Comment by hsz** [comment]
Fixed with `v4.0.0`.
