### ISSUE TITLE
Plugin didn't work for external directories (outside project dir)

### ISSUE THREAD

**Issue by desirepl** [JetBrains/idea-gitignore#569]
### Prerequisites

* [x] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. Create project.
2. Go to Settings > Directory.
3. Add external directory.
4. Right Click on any file/dir in original project directory tree, see that ignore menu/options exist and works, files colored accordingly.
5. Right Click on any file/dir in added external directory tree, see that ignore menu/options didn't exist.
6. Manually edit .gitignore or info\exclude files in project directory, save. Check that files colored in project directory tree but not in added external directory tree.
7. Manually edit .gitignore or info\exclude files in added external directory, save. Check that files colored in added external directory tree didn't applied but in project directory tree applied.

**Reproduces how often:** 
100%

### Versions
**Plugin:** 
v3.0.0.182

**IDE:** 
PhpStorm 2018.3.2
183.4886.46 (any previous version has this bug too)

**OS:** 
Any Windows where PhpStorm can be run.

**Comment by hsz** [comment]
IntelliJ IDEA 2019.2 introduced native support for the dot-ignore files handling of Git (.gitignore), Mercurial (.hgignore), and Perforce (.p4ignore). Because of that, this issue is now obsolete.
