### ISSUE TITLE
Detecting ignored files that are tracked seems broken

### ISSUE THREAD

**Issue by julienfalque** [JetBrains/idea-gitignore#570]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

On a project, I have a root file that is tracked by Git while it is covered by an entry in `.gitignore` file. The entry appears as matched but:
* the file appears as ignored just like any other ignored file;
* the notification balloon never appears;
* the context menu in project panel doesn't show the "untrack ignored files" entry.

### Steps to Reproduce

Create a new empty project in PhpStorm. Initialize a Git repository in the project, add a `test.txt` file and commit it. Add a `.gitignore` file with the following entry `/test.txt` and commit it.

**Expected behavior:**

`test.txt` should appear like any other tracked file.

**Actual behavior:** 

`test.txt` appears like an ignored file.

**Reproduces how often:** 

Always?

### Versions

**Plugin:** 

v3.0.0.182

**IDE:** 

PhpStorm 2018.3.2 (Build #PS-183.4886.46, built on December 19, 2018)

**Java**
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**OS:** 

Ubuntu 18.04 (Linux 4.15.0-43-generic)

**Comment by stdedos** [comment]
Probably related:
![Screenshot from 2019-05-29 13-38-11](https://user-images.githubusercontent.com/133706/58550751-264dc380-8217-11e9-968d-e77a4cfba86b.png)

![Screenshot from 2019-05-29 13-38-04](https://user-images.githubusercontent.com/133706/58550758-28178700-8217-11e9-92dc-b0d8ef96c313.png)
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
Empty, cannot expand
```.gitignore
docker/pip-packages
/terraform
ansible/env

# Python virtual environment
.venv

## Jetbrains
# If wanted, someone can add a project codestyle or dictionary in the future
# Ignore the whole directory for now
.idea

# https://stackoverflow.com/a/42571739/2309247
# User-specific stuff:
.idea/workspace.xml
.idea/tasks.xml
.idea/dictionaries
.idea/vcs.xml
.idea/jsLibraryMappings.xml

# Sensitive or high-churn files:
.idea/dataSources.ids
.idea/dataSources.xml
.idea/dataSources.local.xml
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml

# File-based project format:
*.iws
```

**Comment by hsz** [comment]
Closing due to removing this feature at all with v3.1.2
