### ISSUE TITLE
Add .ignore plugin back to IntelliJ Notifications

### ISSUE THREAD

**Issue by dslove** [JetBrains/idea-gitignore#578]
### Prerequisites

MacOS Mojave v10.14.3
IntelliJ Ultimate Edition 2018.3.5
.ignore v2.6.2

### Description

One of my projects will show "ignored file found being tracked by Git" or sth similar as a pop-up notification in Event Log in IntelliJ when I open this project. One day, that is, today, I clicked the "don't show" link in the notification by mistake and suddenly this notification disappear forever. I went to the Preference-Notification setting and found the ".ignore plugin" is no longer in the list to enable logs. I am wondering how to add it back to the notification list so that I can still get the warning.

I tried re-install .ignore and restart IntelliJ and it didn't help.

**Comment by dslove** [comment]
[IDEA-210334] (https://youtrack.jetbrains.com/issue/IDEA-210334) is also created for this issue but I am wondering if .ignore should also look into this too.

**Comment by dslove** [comment]
The IntelliJ team pointed out another place to look for the missing information: Preference -> Version Control -> Ignore Files Support & Ignored Files, but still we don't have a way to add .ignore plugin back to the notification list. However, as I said in IntelliJ Youtrack, this sounds to be a trivial feature, and I don't know which party should be responsible for it, IJ or .ignore.
I am fine to either close this issue or keep it open to track this small enhancement.

**Comment by hsz** [comment]
@dslove
 _ignored file found being tracked by Git_ notification (with the feature connected with it) as well as the ones about updates have been removed from the project.
Your problem should not be valid anymore.
