### ISSUE TITLE
Misinterpretation of the Slash at .gitignore Pattern Start

### ISSUE THREAD

**Issue by ktomk** [JetBrains/idea-gitignore#584]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet

### Description

When editing a `.gitignore` file typing a slash ("`/`") at the beginning of a pattern offers file- and
directory-name-completion to the root of the project regardless in which project directory the `.gitignore` in the editor is located.

### Steps to Reproduce

1. Edit a `.gitignore` file in a sub-directory (create it and the directory if needed)
2. Insert a new line and type "/"
3. Completion menu pops-up

**Expected behavior:** Offer completion of file and directory names of the same directory the `.gitignore` file is placed in (lower level overrides higher level for `.gitignore`).

**Actual behavior:**  The completion offers file and directory names of the projects root (toplevel) directory.

**Reproduces how often:** Always

### Versions

**Plugin:** 2.6.2

**IDE:** 

```
PhpStorm 2019.2 EAP
Build #PS-192.5118.33, built on June 13, 2019
PhpStorm EAP User
Expiration date: July 13, 2019
Runtime version: 11.0.3+12-b304.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-51-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1631M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: FrameSwitcher, com.paperetto.dash, com.shellcheck, mobi.hsz.idea.gitignore, BashSupport, com.intellij.plugins.html.instantEditing, com.kalessil.phpStorm.phpInspectionsEA, lv.midiana.misc.phpstorm-plugins.deep-keys, me.artspb.idea.eval.plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv
```

**OS:** 

```
Linux 4.15.0-51-generic #55-Ubuntu SMP 
Wed May 15 14:27:21 UTC 2019 
x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

Expected behavior is documented in the [Git docs for *gitignore* in its _Description_](https://git-scm.com/docs/gitignore#_description), specifically:

> * Patterns read from a `.gitignore` file in the same directory as the path, or in any parent directory, with patterns in the higher level files (up to the toplevel of the work tree) being overridden by those in lower level files down to the directory containing the file. **These patterns match relative to the location of the `.gitignore` file** [bold by me]. A project normally includes such `.gitignore` files in its repository, containing patterns for files generated as part of the project build.

and additionally for the meaning of the slash character [in the _Pattern_ section](https://git-scm.com/docs/gitignore#_pattern_format), specifically:

> * A leading slash matches the beginning of the pathname. For example, "/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".

(all excerpts from docs Version 2.22.0)

**Comment by ktomk** [comment]
I'm just asking myself if this been reviewed by the project maintainers?  Reporting day was June 20th and not even a comment, this just makes me wonder if.

**Comment by dmitriysmirnovjb** [comment]
Since IntelliJ 2019.2 completion in gitignore files is provided by the platform. It works correctly there.

There is no need in the .ignore plugin to have .gitingore status highlighting, completion and Add to .gitignore action. However, the plugin still provides some additional features. v.3.2.2 is compatible with 2019.2

**Comment by ktomk** [comment]
@dmitriysmirnovjb Thanks for the update und clarification.
