### ISSUE TITLE
Incorrect parsing of ${} symbols in gitignore

### ISSUE THREAD

**Issue by timothybasanov** [JetBrains/idea-gitignore#585]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Using a mix of `$`, `{` and `}` symbols within `.gitignore` files causes a parsing error within a plugin.

### Steps to Reproduce

Create a `.gitignore` file with this contents:
```
${}/
```

**Expected behavior:** Valid gitignore file that ignores all directories named (literally) `${}`.

**Actual behavior:** Error syntax highlight within a file:

<img width="575" alt="Screen Shot 2019-06-20 at 3 55 27 PM" src="https://user-images.githubusercontent.com/991036/59886460-e55b5180-9373-11e9-82d2-979c102243b9.png">

**Reproduces how often:** Always reproducible

### Versions

**Plugin:** 
```
3.1.2.191
```

**IDE:** 
```
IntelliJ IDEA 2019.1.3
```

**OS:** 
```
macOS Mojave 10.14.5, up to date as of June 20th
```

**Comment by hsz** [comment]
@timothybasanov Thank you for creating this issue! It's fixed and will be available with upcoming release.

**Comment by dmitriysmirnovjb** [comment]
released
