### ISSUE TITLE
Nested wildcard exclusion ignores wrong paths

### ISSUE THREAD

**Issue by AlexHaaniWink** [JetBrains/idea-gitignore#586]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. Create a file structure and `.gitignore` file contents as below.
2. Start PhpStorm on the `test` directory.
3. Then check the Project file tree.

#### file structure (last elements are files):
```
test/foo/baz/ignored_dir
test/foo/custombar/not_ignored_dir
```

#### .gitignore contents
```
foo/*
!foo/custom*
```

**Expected behavior:**

The directory `custombar` AND it's contents are NOT marked as ignored.

**Actual behavior:** 

The directory `custombar` is not marked as ignored (good).
But the file `foo/custombar/not_ignored_dir` is marked as ignored (bad).

**Reproduces how often:** 

Every time

### Versions

**Plugin:** 

```
v3.1.2.191
```

**IDE:** 

```
PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
Licensed to iWink / Alex Haan
Subscription is active until December 9, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.0-9-amd64
```

**OS:** 

```
Debian 9
kernel: 4.9.0-9-amd64
```

### Additional Information

Sure. We could also add
```
!foo/custom*/*
```

But if I try to commit with just the initial, then PhpStorm does see `foo/custombar/not_ignored_dir` as a new file.

**Comment by ktomk** [comment]
I also found the pattern parser broken for  GIT `.gitignore` files, the issue is https://github.com/JetBrains/idea-gitignore/issues/584 .  I can imagine the actual information to which base path (`dirname`)  a `.gitignore`'s pattern is absolute / relative to is with flaws.

**Comment by dmitriysmirnovjb** [comment]
Since IntelliJ 2019.2 highlighting of gitignored files is provided by the platform. It relies on git status output and thus highlights the mentioned case correctly.

There is no need in the .ignore plugin to have .gitingore status highlighting, completion and Add to .gitignore action. However, the plugin still provides some additional features. v.3.2.2 is compatible with 2019.2
