### ISSUE TITLE
Incompatible with 2019.2

### ISSUE THREAD

**Issue by Atulin** [JetBrains/idea-gitignore#587]
![image](https://user-images.githubusercontent.com/11233299/61683573-3d3ffc00-ad16-11e9-8220-a2e5db53a688.png)

Will most probably break in all other IDEs when IntelliJ starts pushing their respective 2019.2 updates.

**Comment by mindyourlifeguide** [comment]
similar problem

**Comment by nazrhyn** [comment]
JetBrains added a built-in .ignore support Plugin in 2019.2. Similar thing happened with BashSupport:   
https://www.bashsupport.com/news/bashsupport-future/

I suppose we'll see what happens here.

**Comment by dmitriysmirnovjb** [comment]
Starting with 2019.2 all IntelliJ-based IDEs have builtin handling for gitignore and hgignore, which overlaps with the .ignore plugin functionality. That is why the compatibility of the .ignore plugin was limited. Please see https://blog.jetbrains.com/idea/2019/07/support-for-vcs-ignores-in-intellij-idea-and-intellij-based-ides/ for details.

We plan to release a new version compatible with 2019.2 and later versions which will provide extended features (like .dockerignore support, etc), but will not conflict with builtin gitingore support.

**Comment by mindyourlifeguide** [comment]
Thanks for your work!

**Comment by alantang888** [comment]
I like .ignore plugin more then the new build-in function. Because the build-in function missed some features (or I didn't discovery the setting yet :P). Like: 

- Can't hide ignored files
- Can't generate a template by just select what you want. (I only found the build-in fuction have to click file one by one)

**Comment by dmitry-ivanov** [comment]
And the colored highlighting within the `.gitignore` file was really nice, which is missing in the built-in IDE functionality.

**Comment by dmitriysmirnovjb** [comment]
There was no goal to replicate all feature of the .ignore plugin in the builtin integration. We also do not plan to completely drop .gitignore-related features from the .ignore plugin, only those that conflict with builtin things. The plugin still will provide some feature like ignore file generation from a template, etc.

And this is not the right place to complain about missing IntelliJ feature, I believe. If you want to see some features in the IDE, please submit a request to https://youtrack.jetbrains.com/issues/IDEA

**Comment by kevincam3** [comment]
We gotta get this back ASAP. I'm thinking of downgrading PhpStorm so I can get this back. Bad call to not have this working.

**Comment by nazrhyn** [comment]
>And this is not the right place to complain about missing IntelliJ feature, I believe.
I think what they were saying is they like your plugin more than the new builtin plugin. And that they miss it 😢. Me too.

**Comment by senid231** [comment]
I like that this plugin allows to see/edit `.git/info/exclude` when open `.gitignore`.
Thank you for your work

**Comment by dmitriysmirnovjb** [comment]
.ignore v3.2.0 is released, compatible with 2019.2. After a short verification, as usual, it will become available in the Marketplace https://plugins.jetbrains.com/plugin/7495--ignore

**Comment by jraller** [comment]
v.3.2.0 causes PhpStorm 2019.2 to report an error on loading. In the error dialog it stills shows plugin ownership as hsz rather than JetBrains preventing the error report from being sent directly.

![image](https://user-images.githubusercontent.com/312810/62332660-4b5bee00-b475-11e9-8d03-9482bbf3d043.png)

**Comment by dmitriysmirnovjb** [comment]
As a worakround please enable hg4idea (Mercurial) plugin. See #592
