### ISSUE TITLE
right click donot show 'add to ignore file'

### ISSUE THREAD

**Issue by learnprogram2** [JetBrains/idea-gitignore#590]
right click on one file, it don't show 'add to ignore file', only show 'show ignored files'.
    when open 'setting'->'appearance&behavior'->'menus and toolbars', edit 'scope view popup menue'-> 'project view popup menu' , can see 'add to ignore file', but it's icon was a 'folder' icon.
    i m confused

**Comment by hsz** [comment]
@learnprogram2 Please follow the issue template.

**Comment by inside-the-sandbox** [comment]
I noticed that the .ignore plugin is not supported by Intellij 2019.2

**Comment by dmitriysmirnovjb** [comment]
Ignore plugin is indeed not compatible with 2019.2 yet, see #587

**Comment by dmitriysmirnovjb** [comment]
Duplicate of #587
