### ISSUE TITLE
Exception in Webstorm after plugin update

### ISSUE THREAD

**Issue by zr87** [JetBrains/idea-gitignore#600]
### Prerequisites

* [x ] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:**

**Actual behavior:** 

**Reproduces how often:** 

### Versions

**Plugin:** 

**IDE:** 

**OS:**

**Comment by hsz** [comment]
Duplicate of #592 
Please read https://github.com/JetBrains/idea-gitignore/issues/592#issuecomment-518369673 for more information regarding the problem, workaround and releasing the fix.
