### ISSUE TITLE
Plugin Error: Plugin ".ignore" is incompatible (target build range is 192 to 193).

### ISSUE THREAD

**Issue by phoenix-schwarz** [JetBrains/idea-gitignore#610]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [-] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:**

**Actual behavior:** 

**Reproduces how often:** 

### Versions

**Plugin:** 

**IDE:** 

**OS:**

**Comment by dmitriysmirnovjb** [comment]
v.3.2.3 compatible with 193 has been released
