### ISSUE TITLE
Add support for Eleventy ignore files

### ISSUE THREAD

**Issue by drubb** [JetBrains/idea-gitignore#611]
Eleventy is a static site generator. It uses .eleventyignore files to exclude files from the internal build process:

https://www.11ty.io/docs/ignores/

AFAIK globs are processed by fast-glob.

**Comment by samuel-velazquez** [comment]
Last float and verticall for binary state do schedule so parameter also component () method

**Comment by samuel-velazquez** [comment]
theme is process and getso drawing function and capcha is developer usager only draft: do component is region bolt are model

**Comment by hsz** [comment]
`.eleventyignore` (11ty) support is now implemented and will be available since `v4.1.0`.
