### ISSUE TITLE
The "Close ignored" option has disappeared from the context menu when right cliking a tab

### ISSUE THREAD

**Issue by Taitava** [JetBrains/idea-gitignore#612]
### Prerequisites

* [x] Plugin is in the latest version (version is 3.2.3.193)
* [x] Issue was not reported yet (tried to search for "close ignored")
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

See this screenshot:
![image](https://user-images.githubusercontent.com/13002142/69905331-d8c73480-13ba-11ea-81ea-418319b7e700.png)

There used to be a menu item called "Close ignored", but it's gone.

**Reproduces how often:** 

I think this reproduces every time I use this context menu.

### Versions

**Plugin:** 
```
3.2.3.193
```

**IDE:** 

```
PhpStorm 2019.3
Build #PS-193.5233.101, built on November 28, 2019
Licensed to IT-Palvelu Taitava / Jarkko Linnanvirta
Subscription is active until March 27, 2020
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-70-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 928M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, search.everywhere.configurations=false, search.everywhere.settings=true, search.everywhere.toolwindows=false
Non-Bundled Plugins: com.intellij.plugins.html.instantEditing, BashSupport, com.alayouni.ansiHighlight, com.intellij.ideolog, com.intellij.lang.jsgraphql, com.raket.silverstripe, com.smartbit8.laravelStorm.intellij, com.thanosp.phpstorm.inheritdoc, com.vladsch.idea.multimarkdown, com.yii2support, lv.midiana.misc.phpstorm-plugins.deep-keys, mobi.hsz.idea.gitignore, org.jetbrains.plugins.rest, ru.adelf.idea.dotenv
```

**OS:** 

```
Xubuntu 16.04
```

**Comment by ZHOUXING1997** [comment]
I encountered the same problem and solved it after I installed a plug-in

![image](https://user-images.githubusercontent.com/33240857/163306081-c697f205-703e-481c-847c-67cccdec3f93.png)
