### ISSUE TITLE
can't display default icon

### ISSUE THREAD

**Issue by Leviathans** [JetBrains/idea-gitignore#618]
<img width="268" alt="WX20200215-152227@2x" src="https://user-images.githubusercontent.com/2937307/74583909-60f6c680-5007-11ea-8b95-27bfd9610812.png">

idea version :2019.3
os:mac os 10.15.3

**Comment by hsz** [comment]
The .ignore plugin doesn't support Git/Mercuria anymore since such functionality is provided natively by the IDE.
