### ISSUE TITLE
Add support for DeployHQ ignore file

### ISSUE THREAD

**Issue by marcandreappel** [JetBrains/idea-gitignore#619]
DeployHQ has support for .deployignore files, which serve the purpose of ignoring files or folders, and eventually whitelistening files in ignored folder; more over here: [DeployHQ: Excluded files](https://www.deployhq.com/support/excluded-files).

This really would be a nice addition, to be able to right-click on a file / folder and to add it to the .deployignore file.

**Comment by hsz** [comment]
`.deployignore` (DeployHQ) support is now implemented and will be available since `v4.1.0`.
