### ISSUE TITLE
Will the "tracked & ignored" feature come back in the future?

### ISSUE THREAD

**Issue by RalphBergmannKMB** [JetBrains/idea-gitignore#620]
One of the best features, for me, was the "tracked & ignored" feature. But it was removed with v3.1.2 or so.

Do you have plans to bring it back?

**Comment by hsz** [comment]
I'm sorry, but that feature will not be brought back. Under the hood, it caused many performance troubles; besides, the Git/Mercurial support is now provided by the IDE itself, and such functionalities have been extracted from the .ignore plugin.
