### ISSUE TITLE
Plugin is incompatible IntelliJ IDEA 2020.2 EAP

### ISSUE THREAD

**Issue by shabtaisharon** [JetBrains/idea-gitignore#628]
![image](https://user-images.githubusercontent.com/14626506/83170852-6bc6fa00-a0d2-11ea-98e8-1bfc93e466a6.png)

**Comment by WuglyakBolgoink** [comment]
22.06.20 still broken (

**Comment by stevencrader** [comment]
The first RC is now available. Any idea when a version supporting 2020.2 will be released?

**Comment by BorzdeG** [comment]
the fix from @shabtaisharon works fine - build and installed the plugin locally. We are waiting for the PR

**Comment by stevencrader** [comment]
Thank you. I was able to build the fixed version.

**Comment by thestelz** [comment]
The newest WS release isn't supported. Not sure if this is the right issue to add on to or if it should be it's own issue.

```
WebStorm 2020.2
Build #WS-202.6397.88, built on July 24, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.13
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: ide.allow.merge.buttons=false

```

<img width="733" alt="WS_Ignore" src="https://user-images.githubusercontent.com/1774502/88540399-d9af7500-cfe0-11ea-8161-d258a5f8c7a8.png">

**Comment by huehnerlady** [comment]
Newest IDEA release 2020.2 is not supported either
