### ISSUE TITLE
Plugin Breaks Next Highlighted Error Functionality

### ISSUE THREAD

**Issue by dehrk** [JetBrains/idea-gitignore#629]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Installing .ignore 3.2.3.201 causes the Next Highlighted Error functionality (default shortcut F2) to continue moving through a file even when there are no errors. Without the plugin, a file with no errors will display the message `No errors found in this file` when pressing F2.

### Steps to Reproduce

1. Open a file with no errors highlighted
2. Use the Next Highlighted Error Function

**Expected behavior:**

Editor should pop up the message `No errors found in this file`

**Actual behavior:** 

Cursor moves continuously through the file

**Reproduces how often:** 

100% of the time as long as there are no background processes running

### Versions

**Plugin:** 

````
3.2.3.201
````

**IDE:** 

````
PhpStorm 2020.1.2
Build #PS-201.7846.90, built on June 3, 2020
Licensed to Derek Kinney
You have a perpetual fallback license for this version
Subscription is active until April 26, 2021
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1478M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: CMD Support, com.ppolivka.plugin.gitcleaner, zielu.gittoolbox, com.mallowigi, io.github.biezhi.plugins.gitmoji, net.codestats.plugin.atom.intellij, NEON support, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, com.kalessil.phpStorm.phpInspectionsUltimate, net.king2500.plugins.PhpAdvancedAutoComplete, org.psliwa.idea.composer, izhangzhihao.rainbow.brackets, some.awesome
````

**OS:** 

````
Windows 10 Enterprise 1803
````

**Comment by hsz** [comment]
@dehrk Thanks for reporting! Could you please check if this problem occurs also in the latest `v4.0.4`?

**Comment by dehrk** [comment]
The issue is no longer present. Thanks.
