### ISSUE TITLE
[Feature Request] Add Support for .tokeignore files

### ISSUE THREAD

**Issue by Redfire75369** [JetBrains/idea-gitignore#640]
# Adding Support for Tokei Ignore files

Tokei is a command-line utility that displays statistics about the code in a project.
`.tokeignore` files can be used to make it ignore certain folders of files. It uses the same syntax as `.gitignore` so it should be simple to add it.

Github Repository: https://github.com/XAMPPRocky/tokei

**Comment by hsz** [comment]
.tokeignore (Tokei) support is now implemented and will be available since v4.1.0.
