### ISSUE TITLE
Why this plugin never compatible with the latest idea?

### ISSUE THREAD

**Issue by FlatMapIO** [JetBrains/idea-gitignore#641]

**Comment by davichi11** [comment]
Too Busy？

**Comment by K2ouMais** [comment]
Yes... New PHPStorm 2020.3 came out and the only plugin not compatible ist this one. ;o(

**Comment by JorisDebonnet** [comment]
True... but #637 mentions that the update will likely land next week.

**Comment by edoger** [comment]
I just upgraded Goland and encountered the same problem~

**Comment by f1amy** [comment]
All of my installed plugins are forward compatible by default, well except this one...

**Comment by jacob418** [comment]
I always keep the former version of PHPStorm installed in case I need to generate a `.gitignore` in some projct. Of course this is unpleasent but how often does one need to generate a new `.gitignore`?

**Comment by hsz** [comment]
I just posted the current status of works here: https://twitter.com/hszanowski/status/1335306406682103808
Stay tuned!

I'll mark that issue as a duplicate of #637 to keep this board clean.
