### ISSUE TITLE
.Ignore not working for IntelliJ IDEA 2020.3

### ISSUE THREAD

**Issue by mehdimonemi** [JetBrains/idea-gitignore#644]
The error text by the IntelliJ IDEA:
Plugin error: Plugin '.ignore' (version 'null') is not compatible with the current version of the IDE, because it requires build 203 or older but the current build is IU-203.5981.155

**Comment by mems** [comment]
Duplicate #637

**Comment by dmitriysmirnovjb** [comment]
Duplicate of #637
