### ISSUE TITLE
[Feature Request] "Generate to clipboard"

### ISSUE THREAD

**Issue by maartenba** [JetBrains/idea-gitignore#647]
### Description

In the "Generate" dialog, I would love to see a "Generate to clipboard" action. This may help in some cases where I have an existing project open, but want to quickly generate a .ignore file to be used elsewhere ("edit in browser" on various git platforms being one).

**Comment by hsz** [comment]
Feature will be delivered with `v4.1.0`.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/108333/114161548-80963000-9928-11eb-8986-512ddaa756d4.png">
