### ISSUE TITLE
.eslintignore icon

### ISSUE THREAD

**Issue by stlr00** [JetBrains/idea-gitignore#650]
.eslintignore icon is colored, while other ignore icons is not

![image](https://user-images.githubusercontent.com/61075639/102228828-2fd37500-3efc-11eb-8e9d-9b9fbc100214.png)

**Comment by hsz** [comment]
Looks like it's overwritten by some other plugin.
.ignore provides b&w icons only: https://github.com/JetBrains/idea-gitignore/blob/master/src/main/resources/icons/icon_eslint%402x.png

**Comment by stlr00** [comment]
I think it`s overwritten by Webstorm includes Eslint support, cause it is this icon. Of course all additional plugins disabled.
When I create .eslintignore first one second icon takes from .ignore plugin, but after icon overwritten by Webstorm
![image](https://user-images.githubusercontent.com/61075639/102243694-8052ce80-3f0c-11eb-98e1-ccda38c41996.png)

**Comment by stlr00** [comment]
Check it please
