### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by AlexPl292** [JetBrains/idea-gitignore#651]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Search is broken for ignore.

### Steps to Reproduce

1. Click new file -> gitignore
2. Search for `rust` or `vim`.

**Expected behavior:**

Correct items should be shown.

**Actual behavior:** 

Random unrelated items are shown.

**Reproduces how often:** 

### Versions

**Plugin:** 
4.0.2

**IDE:** 
IntelliJ IDEA 2020.3.1 RC (Ultimate Edition)
Build #IU-203.6682.115, built on December 23, 2020
Licensed to JetBrains Team / Alex Plate
You have a perpetual fallback license for this version.
Subscription is active until January 10, 2022.
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: debugger.compiling.evaluator.extract.generated.class=false, ide.plugins.snapshot.on.unload.fail=true, analyze.exceptions.on.the.fly=true, external.system.auto.import.disabled=true, debugger.watches.in.variables=false, actionSystem.win.suppressAlt.new=false, vcs.commit.tool.window=false, ide.plugins.allow.unload.from.sources=true, ide.new.project.model.indicator=true
Non-Bundled Plugins: AceJump, IdeaVIM, org.jetbrains.IdeaVim-EasyMotion, PlantUML integration, com.intellij.ideolog, com.intellij.nativeDebug, com.intellij.plugin.copy.options, me.artspb.idea.build.number.plugin, me.artspb.hackathon.git.bisect.run, org.nik.presentation-assistant, org.toml.lang, SpotProfiler, com.jetbrains.embeddedProjectJdk, jetbrains.team.auth, org.jetbrains.idea.grammar, Jetbrains TeamCity Plugin, org.jetbrains.kotlin, com.jetbrains.intellij.api.watcher, com.jetbrains.space, io.ktor.intellij.plugin, MetricsReloaded, izhangzhihao.rainbow.brackets, org.rust.lang, mobi.hsz.idea.gitignore

**OS:** 
MacOS

### Additional Information

![2020-12-27 21 23 52](https://user-images.githubusercontent.com/4203721/103177322-64471980-488a-11eb-8e7d-8ffa4e48430c.gif)
![2020-12-27 21 24 37](https://user-images.githubusercontent.com/4203721/103177323-66a97380-488a-11eb-8053-d0000b665a30.gif)

**Comment by hsz** [comment]
Thanks, @AlexPl292!
Fix will be available in `v4.0.3`.
