### ISSUE TITLE
Favorites Are Broken

### ISSUE THREAD

**Issue by SturmB** [JetBrains/idea-gitignore#653]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Clicking the star icon ("Add Template to Favorites") appears to have no effect until you close the dialog box and re-launch it.

In addition, If you add another template to Favorites after re-launching the dialog, the previously favorited templates disappear. Like before, however, this change doesn't appear until re-launching the dialog.

### Steps to Reproduce

1. Select a Template from the "Ignore File Generator" dialog.
2. Click the "Add Template to Favorites" button (the star icon)
3. Notice that your new favorite template does not appear under "Starred templates."
4. Close and re-launch the "Ignore File Generator" dialog.
5. Notice that the aforementioned template **now** appears under "Starred templates."
6. Add a second template to favorites. Notice that it does not appear in the "Starred templates" list.
7. Close and re-launch the "Ignore File Generator" dialog.
8. Notice that your **first** favorite has disappeared, but the **second** favorite is now on the list.

**Expected behavior:**

I would expect the template to appear immediately under "Starred templates" upon clicking the star button and that no previously-starred templates would disappear without explicitly removing them from the "Starred templates" list.

**Actual behavior:** 

The template is added, but it is not visible under "Starred templates" until the dialog has been refreshed. Once refreshed, any previous favorites will be removed once a new favorite is added to the list.

**Reproduces how often:** 

100% of the time. Every time.

### Versions

**Plugin:** 

```
4.0.2
```

**IDE:** 

```
PhpStorm 2020.3.1
Build #PS-203.6682.180, built on December 30, 2020
```

**OS:** 

```
MS Windows 10 v2004
OS build 19041.685
```

### Additional Information

Can't think of any. Please let me know if you need anything else.

**Comment by hsz** [comment]
Chris, thanks for reporting! It's fixed and will be released with `v4.0.3`.
