### ISSUE TITLE
Mention EAP channel in plugin overview

### ISSUE THREAD

**Issue by solonovamax** [JetBrains/idea-gitignore#660]
## Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

## Description

Unless you navigate to the plugin repo and open the closed issues tab & search for it, it's hard to learn about the EAP channel.
You don't need anything fancy, just copy what you have in the README to the plugin description.

**Expected behavior:**

It'd be great if you could have some nice big text saying 
> ### If you are using an EAP version of IntelliJ, you need to switch to the EAP channel. Here is how you do it: ...
in the overview on the plugin page (so it shows in the IDE)

**Actual behavior:** 

There is no "do this to have it work with the EAP builds" section.

**Reproduces how often:** 

always

### Versions

**Plugin:** 

the latest lol

**IDE:** 

doesn't matter (but if you're running into the issue, you're on an EAP version)

**OS:** 

TempleOS

### Additional Information

none

**Comment by hsz** [comment]
@solonovamax that's a good point, thanks.

**Comment by hsz** [comment]
https://github.com/JetBrains/idea-gitignore#early-access-preview
