### ISSUE TITLE
Icon of .gitignore file is not shown in IntelliJ Ultimate

### ISSUE THREAD

**Issue by theseagull** [JetBrains/idea-gitignore#668]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. install .ignore plugin
2. create a gitignore file via dialog
3. inspect the icon of the newly generated file

**Expected behavior:**

**Actual behavior:** does not show proper icon

**Reproduces how often:** 20 times

100%

### Versions

Non-Bundled Plugins: mobi.hsz.idea.gitignore, org.jetbrains.kotlin

**Plugin:** 

**IDE:** 

**OS:** 

### Additional Information

this picture shows what is currently presented on the ui:
![gitignoreError](https://user-images.githubusercontent.com/22479691/108901255-ed749580-761a-11eb-9b6b-6b0a095d4896.png)
this picture shows how it is supposed to look like:
![gitignoreError2](https://user-images.githubusercontent.com/22479691/108901376-1563f900-761b-11eb-935c-745e6aa44206.png)

**Comment by theseagull** [comment]
the only properly iconed file is the one for dockerignore.
even the .npmignore is not showing up properly.
so I assume that there is something wrong witht he association to the respective icons.

**Comment by hsz** [comment]
@theseagull, thanks for reporting. Unfortunately, `.gitignore` file is now handled by the IDE, which doesn't provide an icon for such files.
Could you please file an issue in [YouTrack](https://youtrack.jetbrains.com/newIssue)?

**Comment by theseagull** [comment]
youtrack issue opened as requested
https://youtrack.jetbrains.com/issue/IDEA-266579
Thx Mario

**Comment by hsz** [comment]
Thank you, Mario!
