### ISSUE TITLE
Bring back .git/info/exclude split window

### ISSUE THREAD

**Issue by liurui39660** [JetBrains/idea-gitignore#673]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

In old versions of this plugin, `.git/info/exclude` and also the global ignore file are also shown in the split window of the `.gitignore`, which is very convenient if we want to ignore files locally. In later versions, this feature was removed, I'd request to bring this back, or as an option.

### Steps to Reproduce

1. Open or create a `.gitignore` file

**Expected behavior:**

`.git/info/exclude` and the global ignore file content are in the split window.

**Actual behavior:** 

There's no split window.

**Reproduces how often:** 

Always (100%)

### Versions

**Plugin:** 4.0.3

**IDE:** CLion 2020.3.2

**OS:** Windows 10 Pro

### Additional Information

None

**Comment by hsz** [comment]
Thanks for reporting. Git support is now completely provided by the IDE (except syntax highlighting and template providing).
Please vote and track the following ticket: https://youtrack.jetbrains.com/issue/IDEA-92312
