### ISSUE TITLE
[Feature Request] Add Support for .vercelignore file

### ISSUE THREAD

**Issue by zengxs** [JetBrains/idea-gitignore#676]
Vercel (<https://vercel.com>) is a very popular FaaS provider.

`.vercelignore` file can be used to make it prevent uploading certain folders on deployment.

And it use same syntax as `.gitignore`.

Ref: <https://vercel.com/guides/prevent-uploading-sourcepaths-with-vercelignore>

**Comment by hsz** [comment]
`.vercelignore` (Vercel) support is now implemented and will be available since `v4.1.0`.
