### ISSUE TITLE
Plugin incompatible with DataGrip 2021.1

### ISSUE THREAD

**Issue by sercheo87** [JetBrains/idea-gitignore#682]
### Prerequisites

* [ ] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Error on DataGrip 2021.1
Plugin error: Plugin '.ignore' (version '4.0.3') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is DB-211.6693.68

### Steps to Reproduce

1.Update DataGrip to 2021.1
2. Install plugin gitignore

**Expected behavior:**

Enabled plugin.

**Actual behavior:** 

Disable by incompatibility.

**Reproduces how often:** 

Instantly

### Versions

**Plugin:** 

```
4.0.3
```

**IDE:** 

```
DataGrip 2021.1
Build #DB-211.6693.68, built on March 31, 2021
```

**OS:** 

```
Windows 10 10.0
```

**Comment by Vampire** [comment]
Same for IntelliJ 2021.1

**Comment by krivachy** [comment]
Same for Webstorm 2021.1

**Comment by MarxZhou** [comment]
Me too!

**Comment by mozesa** [comment]
PyCharm recent 2021.1 win version is also affected.

**Comment by hsz** [comment]
`v4.0.4` has just been released.
