### ISSUE TITLE
4.0.4, 4.1.0 doesn't hide .venv folder

### ISSUE THREAD

**Issue by mozesa** [JetBrains/idea-gitignore#686]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
I can see `.venv` folder despite of being declared in `.gitignore` file.

### Steps to Reproduce

1. Install 4.0.4 `gitignore` plugin.

**Expected behavior:**
I don't want to see the `.venv` folder.

**Actual behavior:** 
I can see the `.venv` folder.

**Reproduces how often:** 
100%

### Versions

**Plugin:** 
4.0.4

**IDE:** 
```
PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
```

**OS:** 
```
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
```

### Additional Information
![image](https://user-images.githubusercontent.com/49973426/114147040-93a10400-9918-11eb-8a55-a9acb01820d6.png)
As you can see it works fine with 4.0.4-eap version.

**Comment by pplmx** [comment]
ignore version: 4.1.0
platform: Intellij IDEA Build#IU-211.6693.111, build on April 6, 2021
## for gradle projects: 
- .gradle/
- build/

## for nodejs projects:
- node_modules/


these directories cannot be hidden.

**Comment by mozesa** [comment]
It is true for `v4.1.0` too.

![image](https://user-images.githubusercontent.com/49973426/115191167-5ba07a80-a0e9-11eb-9c83-205073ee58ab.png)

**Comment by pplmx** [comment]
Any progress or difficulty?

**Comment by pplmx** [comment]
I found that all those folders that cannot be hidden were marked as **Excluded** by IDEA. If you manually **cancel exclusion**, it will be hidden again.
I think it is a bug, IDEA marks those folders that need to be hidden as **Excluded**, which is invalid.

**Comment by hsz** [comment]
Due to some performance issues and a lose support for .gitignore, the "Hide ignored files" feature has been removed in favor of [Foldable ProjectView](https://github.com/hsz/intellij-foldable-projectview) plugin
