### ISSUE TITLE
can't add entry to `.npmignore`

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/idea-gitignore#723]
### Prerequisites

* [ ] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

![image](https://user-images.githubusercontent.com/167966/126753154-58b35021-6f7b-4bf3-b1ec-119af84b16d5.png)

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:**

**Actual behavior:** 

**Reproduces how often:** 

### Versions

**Plugin:** 

**IDE:** 

**OS:**

**Comment by hsz** [comment]
Thanks for reporting! Fixed with 32496f0
