### ISSUE TITLE
Add a template for rush.io based mono-repos

### ISSUE THREAD

**Issue by dietergeerts** [JetBrains/idea-gitignore#741]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [N/A] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

There is no template for files that need to be ignored for rush.io tool in the `.gitignore` file. This would be handy.

### Steps to Reproduce

1. Add a new `.gitignore` file (which will add to the existing file, which I still find very weird. I would love to see the previous option returned, where you could add templates through a command with right-click, but that's besides the point here)
2. See that there is no `rush` template available.
3. You now need to custom add these files.

**Expected behavior:**

That a rush.io template is available for convenience. 

**Actual behavior:** 

No template is available, so we need to manually add the ignores

**Reproduces how often:** 

100%

### Versions

**Plugin:** 

**IDE:** 

```
4.3.0
```
**OS:** 

```
N/A
```
### Additional Information

N/A

**Comment by hsz** [comment]
@dietergeerts This plugin doesn't define templates but fetches ones from the https://github.com/github/gitignore
Please contribute to the mentioned project.
