### ISSUE TITLE
Code analysis on .dockerignore runs forever with 100% CPU load

### ISSUE THREAD

**Issue by Vovan-VE** [JetBrains/idea-gitignore#749]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Redirect from [WI-65610](https://youtrack.jetbrains.com/issue/WI-65610).

> I added a `.dockerignore` in project root directory and fill it with appropriate patterns.
> 
> When the `.dockerignore` is opened in current editor tab, it cause CPU load until the tab deactivated or closed. Probably it's because of background code analisys.
> 
> When I try to commit any changes in the `.dockerignore` , the "Performing Code Analysis" stucks on the `.dockerignore` with same CPU load and never ends until I press [Cancel] button.
> 
> The `.dockerignore` file is correct and Docker setup works fine with it. The project where it happens is proprietary. It's a kind of monorepo including backend and frontend parts. Another CRA-based project does not run into similar issue. I have a `tmp~` directory with lots of files (its covered by `*~`), but I already tried to move it away from project, and it didn't help.

### Steps to Reproduce

1. Unknown details in specific project.
2. Add `.dockerignore` to the project root.
3. Open `.dockerignore`.

**Expected behavior:**

Normal CPU usage while I do nothing.

**Actual behavior:** 

About 100% CPU usage while `.dockerignore` editor tab is active.

**Reproduces how often:** 

100% of time when `.dockerignore` is opened and it's active tab.

### Versions

**Plugin:** 
```
4.3.0
```

**IDE:** 
```
PhpStorm 2021.3.2
Build #PS-213.6777.58, built on January 31, 2022
...
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-100-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2002M
Cores: 6
Registry:
    search.everywhere.files=false
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.intellij.RegexpTester (1.0.8)
    mobi.hsz.idea.gitignore (4.3.0)
    intellij.prettierJS (213.6461.6)
    com.eny.i18n (2.6.1)

Current Desktop: XFCE
```

**OS:** 
```
Ubuntu 20.04.4
```

### Additional Information

Logs and `.dockerignore` are attached at [WI-65610](https://youtrack.jetbrains.com/issue/WI-65610).

**Comment by ivanpajic** [comment]
+1 [IDEA-314910](https://youtrack.jetbrains.com/issue/IDEA-314910) reported for this issue.
Ignore plugin version used: 4.4.4.

**Comment by hsz** [comment]
Is it reproducible in 4.5.2?

**Comment by Vovan-VE** [comment]
Sorry, didn't work much in the repository where this issue rised from. Checked just now - v4.5.1, no CPU issue.

**Comment by hsz** [comment]
Thanks, Vladimir! I'll close this issue then. Feel free to open a new one whenever it's necessary!
