### ISSUE TITLE
Incompatible with 2022.2 EAP

### ISSUE THREAD

**Issue by Alexsey** [JetBrains/idea-gitignore#767]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
<img width="545" alt="Screenshot 2022-05-22 at 12 07 54" src="https://user-images.githubusercontent.com/6392013/169687962-f30b0af9-7aed-4907-8caf-f5b81583cc7d.png">

**Comment by Alexsey** [comment]
The latest version is working 2022.2 EAP

**Comment by Vampire** [comment]
@Alexsey I just updated to 2022.2, but there is no compatible version.
4.0.4 is only compatible up to 2021.1.3 and next version 4.4.4 is only compatible with 2022.3 which is not released yet.
So there is currently no version compatible with 2022.2. :-(

**Comment by Alexsey** [comment]
@Vampire Not sure how to help you, but I'm running WebStorm 2022.2.3 and `.ignore` plugin version 4.4.2 - you can try to get a similar configuration. And consider that 2022.3 is going to be released this or next week, so the issue for you will be resolved quite soon anyway. Another option for you would be to install the Release Candidate of your IDE - it should already be available

**Comment by hsz** [comment]
The missing releases are now available again.

**Comment by Vampire** [comment]
Thx, working now. :-)
Actually I thought Alexsey is the maintainer as he resolved the issue. Didn't look at author and role. 🙈
