### ISSUE TITLE
Not Support Android Studio Chipmunk 2021.2.1 patch 1 

### ISSUE THREAD

**Issue by BAndersonMatjik** [JetBrains/idea-gitignore#769]
this is error message show when install plugin
![image](https://user-images.githubusercontent.com/33697266/171573854-badead5e-0337-4098-8840-c4a5422a81e3.png)

**Comment by hsz** [comment]
The .ignore plugin in version `3.x` is obsolete – it looks like there was no suitable `4.x` version for your IDE, and it accidentally picked an old release. Please check if there's `4.x` already available.
