### ISSUE TITLE
Feature Request: Update ignore through wizard

### ISSUE THREAD

**Issue by utahcon** [JetBrains/idea-gitignore#780]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Having an option to generate an ignore file from/with an existing ignore file would be amazing! Often I generate a .gitignore, then need to add a new IDE, or package manger, etc. Having it open in the dialog again would be wonderful!

### Steps to Reproduce

**Expected behavior:**

Right-click for context menu -> Update .ignore file

**Actual behavior:** 

None.

**Comment by hsz** [comment]
Implemented with 30039303d95dd15431b4736bbee268e34e5bb228

**Comment by hsz** [comment]
https://twitter.com/hszanowski/status/1627568656036003840
