### ISSUE TITLE
.gitignore cannot be selected

### ISSUE THREAD

**Issue by dcaldr** [JetBrains/idea-gitignore#783]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
.gitignore option cannnot be selected from add file menu

### Steps to Reproduce

1. right-click folder -> new
2. select .ignore File option
3. try to click .gitignore option

**Expected behavior:**
open dialog creating .gitignore file

**Actual behavior:** 
 cannot be clicked

**Reproduces how often:** 
100%

### Versions

**Plugin:** 
```4.4.0```

**IDE:** 
```CLion 2022.1.3``` and ```CLion 2021.3.2``` (when reverted)

**OS:** 
```Ubuntu 20.04.5 LTS focal```

### Additional Information
Several other options (tested at random) are working

**Comment by hsz** [comment]
Is it reproducible in 4.5.1?

**Comment by dcaldr** [comment]
No, now it works as supposed
