### ISSUE TITLE
.ignore crashes IDE during project opening

### ISSUE THREAD

**Issue by TheFruxz** [JetBrains/idea-gitignore#793]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. _Update plugin_
2. _Open project running 2022.3 Beta (223.7571.4)_
3. _crash_

**Expected behavior:**

That my projects gets opened

**Actual behavior:** 

The IDE crashes during the opening

**Reproduces how often:** 

Infinite, First time it crashes and goes back to home, second time it dies completely

### Versions

**Plugin:** 

```
4.4.3
```

**IDE:** 

```
Build #IU-223.7571.4, built on November 9, 2022

Runtime version: 17.0.5+1-b653.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

**OS:** 

macOS 13.1 Beta (22C5044e)
Apple Silicon / aarch

### Additional Information

/

**Comment by sabruss** [comment]
Yup same here , need to disable extension to make it working again `Build #PS-223.7571.15`

**Comment by hsz** [comment]
My apologies – `v4.4.4` is now released.

**Comment by ThexXTURBOXx** [comment]
This issue is back since 4.4.3 has been re-uploaded: https://plugins.jetbrains.com/plugin/20485--ignore/versions

**Comment by geisterfurz007** [comment]
4.4.3 seems to have been made unavailable again and the IDE updates to 4.4.4 which appears to work well.

**Comment by ThexXTURBOXx** [comment]
@geisterfurz007 Yes, now 4.4.4 is the current release for 2022.3
