### ISSUE TITLE
Show new .ignore file templates in folder

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [JetBrains/idea-gitignore#798]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

By default (I think) the plugin has all new .ignore file templates enabled. It would be nice if there was an option to add the templates to a folder instead of the main context menu, since the menu gets really big now (see included screenshot).

If this is made an optional setting, then I think it should be enabled by default (if all the templates are enabled by default). This will make for a better inital user experience.

I don't know if this issue is application specific. I'm using the latest Rider 2022.3 EAP8 with the new ui enabled. 

<img width="500" alt="gitignore" src="https://user-images.githubusercontent.com/1670232/202894695-26dd51c1-67ec-444b-8f16-041c5d6d1154.png">

**Comment by KoakiMiku** [comment]
same problem.
using Rider 2022.3 with new ui.

**Comment by hsz** [comment]
The issue is caused by an internal Rider change.
The Rider team already fixed it and schedule to release in 2022.3.1:
https://youtrack.jetbrains.com/issue/RIDER-86492
