### ISSUE TITLE
Completely broken on 2022.3.1

### ISSUE THREAD

**Issue by alanbur** [JetBrains/idea-gitignore#808]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

After installing the plugin there is no way of getting it to generate am .ignore file for you as it doesn't appear on the File-> New menu, as per the demo on the plugin homepage.

**Comment by hurycz** [comment]
+1

**Comment by hsz** [comment]
Works fine on:
```
IntelliJ IDEA 2022.3.2 (Community Edition)
Build #IC-223.8617.56, built on January 26, 2023
```

If the issue still exists, please create a new issue providing logs and reproducible scenario.
