### ISSUE TITLE
Feature request: support for .terraformignore

### ISSUE THREAD

**Issue by sdrzazga** [JetBrains/idea-gitignore#815]
### Prerequisites

* [X] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Please consider adding support for  [.terraformignore](https://developer.hashicorp.com/terraform/language/settings/backends/remote#excluding-files-from-upload-with-terraformignore).

**Comment by hsz** [comment]
Added!
