### ISSUE TITLE
Double occurence when staring some template

### ISSUE THREAD

**Issue by lavazais-sylvain** [JetBrains/idea-gitignore#844]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. create a new .ignore file
2. choose. .gitignore file type
3. search for Java in search box
4. click on Java template in the result list
5. click on star button

**Expected behavior:**

only one template become "starred"

**Actual behavior:** 

two template (with the same name) appear in the list of "starred templates"

**Reproduces how often:** 

Everytime (100%)

### Versions

**Plugin:** 

```
4.5.1
```

**IDE:** 

```
IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Build #IU-231.9161.38, built on June 20, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
    decompiler.dump.original.lines=true
    debugger.new.tool.window.layout=true
    search.everywhere.settings=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (231.9161.47)
    com.github.leomillon.uuidgenerator (4.5.1)
    org.intellij.plugins.hcl (231.8109.91)
    org.rust.lang (0.4.197.5401-231)
    com.fernandojimenez.mattecarbon.theme (3.0.0)
    org.jetbrains.plugins.go-template (231.8109.91)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.ideolog (222.1.0.0)
    io.github.huzunrong.project-switcher (2022.3)
    name.kropp.intellij.makefile (231.8109.91)
    com.redhat.devtools.intellij.telemetry (1.0.0.44)
    ir.msdehghan.plugins.ansible (0.92)
    org.jetbrains.plugins.go (231.9161.14)
    com.intellij.kubernetes (231.9011.4)
    com.ivanovych666.intellij.plugin.jsonsorter (1.0.0-beta.3.4)
    PlantUML integration (6.3.0-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    Pythonid (231.9161.38)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.1)
    org.sonarlint.idea (8.4.0.73538)
    com.jetbrains.php (231.9161.47)
    izhangzhihao.rainbow.brackets (2023.2.11)
    ru.adelf.idea.dotenv (2023.1)

Kotlin: 231-1.8.21-IJ9161.38
```

**OS:** 

```
Mac Os X Ventura 13.4.1
```

### Additional Information

Some screenshots:
<img width="823" alt="image" src="https://github.com/JetBrains/idea-gitignore/assets/134276360/05af7a81-a289-4cf0-8eae-30778aa9edcf">
<img width="822" alt="image" src="https://github.com/JetBrains/idea-gitignore/assets/134276360/a58c9a05-9ed8-4f60-a3a0-4998c1c34f06">

screenCast:
https://youtu.be/tt4Wh-2Lt24

**Comment by hsz** [comment]
Please provide all the missing information about Versions.

**Comment by lavazais-sylvain** [comment]
> Please provide all the missing information about Versions.

done

**Comment by hsz** [comment]
Thanks, fixed! I'll release new version soon.
