### ISSUE TITLE
Minor grammar problem in warning message

### ISSUE THREAD

**Issue by cwcowell** [JetBrains/idea-gitignore#868]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

A warning message appears when editing a file that's ignored. This warning message is understandable, but contains a small English grammar error, as described below.

### Steps to Reproduce

1. Enable the .ignore plugin
2. Add a file to `.gitignore` or another ignore file
3. Open the ignored file in the IntelliJ editor
4. See the warning message in a banner across the top of the editor window

**Expected behavior:**

The warning message should say:

> You are editing a file that is ignored

or more succinctly:

> You are editing an ignored file

**Actual behavior:** 

The warning message says:

>You are editing a file which is ignored

![ignore-grammar-screenshot](https://github.com/JetBrains/idea-gitignore/assets/43705622/518f81f4-e919-4914-b5dd-1a323d68c01a)

**Reproduces how often:** 

100% of the time

### Versions

**Plugin:** 

```
4.5.2
```

**IDE:** 

```
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 24, 2023
Licensed to Christopher Cowell
Subscription is active until June 28, 2024.
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.10203.2)
    com.andrey4623.rainbowcsv (2.0.2)
    com.intellij.ideolog (222.1.0.0)
    krasa.CpuUsageIndicator (1.18.0-IJ2023)
    org.jetbrains.plugins.rest (232.8660.88)
    name.kropp.intellij.makefile (232.8660.88)
    com.intellij.grazie.pro (0.3.261)
    com.intellij.ml.llm (232.9826)
    mobi.hsz.idea.gitignore (4.5.2)
    Pythonid (232.10203.10)
    izhangzhihao.rainbow.brackets (2023.3.7)

Kotlin: 232-1.9.20-release-507-IJ10072.27
```

**OS:** 

```
macOS 14.1
```

### Additional Information

Confusing "that" with "which" is an _extremely_ common mistake, even among native English speakers. But there is a difference between the two words, and it can be jarring to see them used incorrectly. For more details on the distinction, see https://www.dictionary.com/e/that-vs-which/.

**Comment by cwcowell** [comment]
Fixed by https://github.com/JetBrains/idea-gitignore/pull/871

**Comment by hsz** [comment]
Thanks, Chris!
